### ISSUE TITLE
Easy to lose data

### ISSUE THREAD

**Issue by kalbers** [omeka/plugin-SimpleVocab#8]
When a user selects an element that has already been populated with data, there can be a lag while the data loads into the text field. If a user clicks the Add/Edit button before the data has loaded, it saves it as a blank form, essentially deleting all data.

Maybe the button can be inactive until an element is selected and the form has been changed?

**Comment by jimsafley** [comment]
Fixed in 3a51ef511d1664740986cdc41744af7371582b0f
